name: Secret Scanning with Gitleaks

on:
  pull_request:
    branches: ['**']
  push:
    branches: [master]
  schedule:
    # Run weekly on Sundays at 00:00 UTC
    - cron: '0 0 * * 0'
  workflow_dispatch:
    inputs:
      full_history:
        description: 'Scan full git history (uses --log-opts=--all)'
        required: false
        type: boolean
        default: false

env:
  # Set to 'true' to scan full git history, 'false' for current HEAD only
  FULL_HISTORY: ${{ github.event.inputs.full_history || 'false' }}
  GITLEAKS_CONFIG: '.gitleaks.toml'

jobs:
  gitleaks:
    name: Gitleaks Secret Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # Fetch full history to enable optional full history scans
          fetch-depth: 0
      
      - name: Install Gitleaks
        run: |
          wget -q https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
          tar -xzf gitleaks_${GITLEAKS_VERSION}_linux_x64.tar.gz
          sudo mv gitleaks /usr/local/bin/
          gitleaks version
        env:
          GITLEAKS_VERSION: '8.21.2'
      
      - name: Run Gitleaks scan
        id: gitleaks
        run: |
          echo "Running Gitleaks with FULL_HISTORY=${{ env.FULL_HISTORY }}"
          
          if [ "${{ env.FULL_HISTORY }}" = "true" ]; then
            echo "Scanning full git history..."
            gitleaks detect \
              --config="${{ env.GITLEAKS_CONFIG }}" \
              --report-format=sarif \
              --report-path=gitleaks.sarif \
              --log-opts="--all" \
              --verbose \
              --exit-code=1
          else
            echo "Scanning current HEAD only..."
            gitleaks detect \
              --config="${{ env.GITLEAKS_CONFIG }}" \
              --report-format=sarif \
              --report-path=gitleaks.sarif \
              --verbose \
              --exit-code=1
          fi
        continue-on-error: false
      
      - name: Upload SARIF report
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: gitleaks.sarif
          category: gitleaks
      
      - name: Upload Gitleaks report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-report
          path: gitleaks.sarif
          retention-days: 30
